{% set version = "3.0.0" %}

{% set cuda_major = environ.get("cuda_compiler_version", "11.2").split(".")[0]|int %}

package:
  name: carterbox-torch-radon
  version: {{ version }}

source:
  url: https://github.com/carterbox/torch-radon/releases/download/v{{ version }}/torch-radon-v{{ version }}.zip
  sha256: 8b2cc1ae62e357517f805b878a8f23aeb9a1c43e09397f79e884d3eb83ef8aaf

build:
  number: 0
  skip: true  # [cuda_compiler_version == "None"]
  skip: true  # [cuda_compiler_version == "10.2"]
  skip: true  # [cuda_compiler_version == "11.0"]
  skip: true  # [cuda_compiler_version == "11.1"]
  # no pytorch on windows in conda-forge, see
  # https://github.com/conda-forge/pytorch-cpu-feedstock/issues/32
  skip: true  # [win]
  rpaths:
    - lib/
  # PyTorch libs are in site-packages intead of with other shared objects
    - {{ SP_DIR }}/torch/lib/

requirements:
  build:
    - {{ compiler('cuda') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - cuda-version {{ cuda_compiler_version }}
  {% if cuda_major == 12 %}
    - cuda-cudart-dev
    - libcufft-dev
    - libcurand-dev
  {% endif %}
    - python
    - pip
    - pytorch
  # We must have the CUDA variant of pytorch
    - pytorch =*=cuda*
    - libtorch
    - setuptools
    - setuptools-scm
    - toml
  run:
    - __cuda
    - python
    - pytorch =*=cuda*
    - scipy
    - numpy

test:
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/carterbox/torch-radon
  summary: 'Tomography operators for Pytorch'
  description: |
    TorchRadon is a PyTorch extension written in CUDA that implements
    differentiable tomography operators.
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carterbox
